export const PHASE_TWO_PERMISSIONS = [
  'USER_VIEW', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE',
  'ROLE_VIEW', 'ROLE_MANAGE', 'AUDIT_LOG_VIEW',
  'WAREHOUSE_VIEW', 'WAREHOUSE_CREATE', 'WAREHOUSE_UPDATE', 'WAREHOUSE_DELETE',
  'PRODUCT_VIEW', 'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE',
  'CATEGORY_VIEW', 'CATEGORY_CREATE', 'CATEGORY_UPDATE', 'CATEGORY_DELETE',
  'SUPPLIER_VIEW', 'SUPPLIER_CREATE', 'SUPPLIER_UPDATE', 'SUPPLIER_DELETE',
  'INVENTORY_VIEW', 'INVENTORY_MANAGE',
  'TRANSFER_VIEW', 'TRANSFER_CREATE', 'TRANSFER_APPROVE', 'TRANSFER_DISPATCH', 'TRANSFER_RECEIVE', 'TRANSFER_CANCEL',
  'RESERVATION_VIEW', 'RESERVATION_CREATE', 'RESERVATION_MANAGE', 'RESERVATION_CONSUME', 'RESERVATION_RELEASE', 'RESERVATION_CANCEL',
] as const;

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  ADMIN: PHASE_TWO_PERMISSIONS,
  WAREHOUSE_MANAGER: ['ROLE_VIEW', 'WAREHOUSE_VIEW', 'WAREHOUSE_UPDATE', 'PRODUCT_VIEW', 'CATEGORY_VIEW', 'SUPPLIER_VIEW', 'INVENTORY_VIEW', 'INVENTORY_MANAGE', 'TRANSFER_VIEW', 'TRANSFER_CREATE', 'TRANSFER_APPROVE', 'TRANSFER_DISPATCH', 'TRANSFER_RECEIVE', 'TRANSFER_CANCEL', 'RESERVATION_VIEW', 'RESERVATION_CREATE', 'RESERVATION_MANAGE', 'RESERVATION_CONSUME', 'RESERVATION_RELEASE', 'RESERVATION_CANCEL'],
  INVENTORY_STAFF: ['WAREHOUSE_VIEW', 'PRODUCT_VIEW', 'CATEGORY_VIEW', 'SUPPLIER_VIEW', 'INVENTORY_VIEW', 'INVENTORY_MANAGE', 'TRANSFER_VIEW', 'TRANSFER_CREATE', 'TRANSFER_DISPATCH', 'TRANSFER_RECEIVE', 'RESERVATION_VIEW', 'RESERVATION_CREATE', 'RESERVATION_MANAGE', 'RESERVATION_CONSUME', 'RESERVATION_RELEASE'],
  VIEWER: ['WAREHOUSE_VIEW', 'PRODUCT_VIEW', 'CATEGORY_VIEW', 'SUPPLIER_VIEW', 'INVENTORY_VIEW', 'TRANSFER_VIEW', 'RESERVATION_VIEW'],
};
