import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from './prisma.service.js';
import type { AuthenticatedUser } from './auth.types.js';
import { AdjustmentType, AdjustStockDto, InventoryListDto, ReceiveStockDto } from './inventory.dto.js';

@Injectable()
export class InventoryService {
  constructor(private readonly prisma: PrismaService) {}
  private page(q: InventoryListDto) { const page = Math.max(1, Number(q.page) || 1); const limit = Math.min(100, Math.max(1, Number(q.limit) || 20)); return { page, limit, skip: (page - 1) * limit }; }
  private status(onHand: number, reorder: number, maximum: number | null) { if (onHand === 0) return 'OUT_OF_STOCK'; if (onHand <= reorder) return 'LOW_STOCK'; if (maximum !== null && onHand > maximum) return 'OVERSTOCK'; return 'IN_STOCK'; }
  private view(item: { id: string; quantityOnHand: number; quantityReserved: number; reorderLevel: number; maximumStockLevel: number | null; updatedAt: Date; product: { id: string; name: string; sku: string; barcode: string | null; category: { id: string; name: string } }; warehouse: { id: string; name: string; code: string; city: string | null } }) { return { ...item, quantityAvailable: item.quantityOnHand - item.quantityReserved, stockStatus: this.status(item.quantityOnHand, item.reorderLevel, item.maximumStockLevel) }; }
  private async assertWarehouse(user: AuthenticatedUser, warehouseId: string) { const warehouse = await this.prisma.warehouse.findUnique({ where: { id: warehouseId } }); if (!warehouse || warehouse.status !== 'ACTIVE') throw new NotFoundException('Warehouse not found or inactive'); if (user.role === 'WAREHOUSE_MANAGER' && warehouse.managerId !== user.id) throw new ForbiddenException('Warehouse access is restricted to assigned warehouses'); return warehouse; }
  private async assertMasterData(user: AuthenticatedUser, warehouseId: string, productId: string) { await this.assertWarehouse(user, warehouseId); const product = await this.prisma.product.findUnique({ where: { id: productId } }); if (!product || !product.isActive || product.status !== 'ACTIVE') throw new BadRequestException('Product not found or inactive'); return product; }
  private include = { product: { select: { id: true, name: true, sku: true, barcode: true, category: { select: { id: true, name: true } } } }, warehouse: { select: { id: true, name: true, code: true, city: true } } } as const;
  async list(q: InventoryListDto, user: AuthenticatedUser) { const { page, limit, skip } = this.page(q); const warehouseIds = user.role === 'WAREHOUSE_MANAGER' ? (await this.prisma.warehouse.findMany({ where: { managerId: user.id }, select: { id: true } })).map((x) => x.id) : undefined; const where = { ...(warehouseIds ? { warehouseId: { in: warehouseIds } } : {}), ...(q.warehouseId ? { warehouseId: q.warehouseId } : {}), ...(q.productId ? { productId: q.productId } : {}), ...(q.categoryId ? { product: { categoryId: q.categoryId } } : {}), ...(q.search ? { product: { OR: [{ name: { contains: q.search, mode: 'insensitive' as const } }, { sku: { contains: q.search, mode: 'insensitive' as const } }, { barcode: { contains: q.search, mode: 'insensitive' as const } }] } } : {}) }; const [items, total] = await Promise.all([this.prisma.inventory.findMany({ where, include: this.include, orderBy: { updatedAt: q.sortOrder === 'asc' ? 'asc' : 'desc' }, skip, take: limit }), this.prisma.inventory.count({ where })]); const data = items.map((x) => this.view(x)).filter((x) => !q.stockStatus || x.stockStatus === q.stockStatus); return { success: true, data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async get(id: string, user: AuthenticatedUser) { const item = await this.prisma.inventory.findUnique({ where: { id }, include: this.include }); if (!item) throw new NotFoundException('Inventory record not found'); await this.assertWarehouse(user, item.warehouseId); return { success: true, data: this.view(item) }; }
  async byWarehouse(warehouseId: string, q: InventoryListDto, user: AuthenticatedUser) { await this.assertWarehouse(user, warehouseId); return this.list({ ...q, warehouseId }, user); }
  async byProduct(productId: string, q: InventoryListDto, user: AuthenticatedUser) { const product = await this.prisma.product.findUnique({ where: { id: productId } }); if (!product) throw new NotFoundException('Product not found'); return this.list({ ...q, productId }, user); }
  async receive(dto: ReceiveStockDto, user: AuthenticatedUser) { await this.assertMasterData(user, dto.warehouseId, dto.productId); return this.mutate(dto.warehouseId, dto.productId, dto.quantity, 'RECEIPT', dto.reason, dto.notes, user); }
  async adjust(dto: AdjustStockDto, user: AuthenticatedUser) { await this.assertMasterData(user, dto.warehouseId, dto.productId); const delta = dto.type === AdjustmentType.ADJUSTMENT_OUT ? -dto.quantity : dto.quantity; return this.mutate(dto.warehouseId, dto.productId, delta, dto.type, dto.reason, dto.notes, user); }
  private async mutate(warehouseId: string, productId: string, delta: number, transactionType: string, reason: string, notes: string | undefined, user: AuthenticatedUser) { try { return await this.prisma.$transaction(async (tx) => { let inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId, productId } } }); if (!inventory) { if (delta < 0) throw new ConflictException('Insufficient available stock'); inventory = await tx.inventory.create({ data: { warehouseId, productId, quantityOnHand: 0, quantityReserved: 0 } }); } const available = inventory.quantityOnHand - inventory.quantityReserved; if (delta < 0 && -delta > available) throw new ConflictException('Insufficient available stock'); const next = inventory.quantityOnHand + delta; const updated = await tx.inventory.updateMany({ where: { id: inventory.id, quantityOnHand: inventory.quantityOnHand, quantityReserved: { lte: next } }, data: { quantityOnHand: next } }); if (updated.count !== 1) throw new ConflictException('Inventory changed concurrently; retry the operation'); const transaction = await tx.stockTransaction.create({ data: { inventoryId: inventory.id, warehouseId, productId, transactionType, quantity: Math.abs(delta), quantityBefore: inventory.quantityOnHand, quantityAfter: next, reason, notes, performedBy: user.id } }); await tx.auditLog.create({ data: { userId: user.id, action: transactionType === 'RECEIPT' ? 'INVENTORY_RECEIVED' : 'INVENTORY_ADJUSTED', entity: 'INVENTORY', entityId: inventory.id, details: { warehouseId, productId, quantity: Math.abs(delta), transactionId: transaction.id, reason } } }); return { success: true, data: { inventoryId: inventory.id, quantityOnHand: next, quantityReserved: inventory.quantityReserved, quantityAvailable: next - inventory.quantityReserved, transactionId: transaction.id } }; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (error) { if (error instanceof ConflictException) throw error; throw new ConflictException('Inventory update could not be completed'); } }
  async lowStock(q: InventoryListDto, user: AuthenticatedUser) { const result = await this.list({ ...q, limit: 100 }, user); return { ...result, data: result.data.filter((x) => x.quantityOnHand <= x.reorderLevel) }; }
  async summary(warehouseId: string | undefined, user: AuthenticatedUser) { if (warehouseId) await this.assertWarehouse(user, warehouseId); const result = await this.list({ warehouseId, limit: 100 }, user); const data = result.data; return { success: true, data: { totalInventoryItems: data.length, totalUnits: data.reduce((sum, x) => sum + x.quantityOnHand, 0), outOfStock: data.filter((x) => x.stockStatus === 'OUT_OF_STOCK').length, lowStock: data.filter((x) => x.stockStatus === 'LOW_STOCK').length, inStock: data.filter((x) => x.stockStatus === 'IN_STOCK').length, overstock: data.filter((x) => x.stockStatus === 'OVERSTOCK').length } }; }
  async history(id: string, user: AuthenticatedUser) { const inventory = await this.get(id, user); const data = await this.prisma.stockTransaction.findMany({ where: { inventoryId: id }, orderBy: { createdAt: 'desc' }, include: { performer: { select: { id: true, name: true, email: true } } } }); return { success: true, data: { inventory: inventory.data, transactions: data } }; }
}
