import { ConflictException, Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from './prisma.service.js';
import { ActiveStatus, CategoryDto, ListDto, ProductDto, ProductStatus, SupplierDto, WarehouseDto } from './master-data.dto.js';
import type { AuthenticatedUser } from './auth.types.js';

@Injectable()
export class MasterDataService {
  constructor(private readonly prisma: PrismaService) {}
  private page(query: ListDto) { const page = Math.max(1, Number(query.page) || 1); const limit = Math.min(100, Math.max(1, Number(query.limit) || 20)); return { page, limit, skip: (page - 1) * limit }; }
  private async audit(userId: string, action: string, entity: string, entityId: string, details?: object) { await this.prisma.auditLog.create({ data: { userId, action, entity, entityId, details } }); }
  private async result<T>(items: T[], total: number, query: ListDto) { const { page, limit } = this.page(query); return { success: true, data: items, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  private sort(sortBy: string | undefined, allowed: string[]) { return allowed.includes(sortBy ?? '') ? sortBy! : allowed[0]; }
  private async manager(managerId?: string) { if (!managerId) return; const user = await this.prisma.user.findUnique({ where: { id: managerId } }); if (!user || !user.isActive) throw new BadRequestException('Manager must be an active user'); }
  async warehouses(query: ListDto) { const { limit, skip } = this.page(query); const where = { ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' as const } }, { code: { contains: query.search, mode: 'insensitive' as const } }] } : {}), ...(query.status ? { status: query.status } : {}) }; const [data, total] = await Promise.all([this.prisma.warehouse.findMany({ where, include: { manager: { select: { id: true, name: true, email: true } } }, orderBy: { [this.sort(query.sortBy, ['name', 'code', 'updatedAt'])]: query.sortOrder === 'desc' ? 'desc' : 'asc' }, skip, take: limit }), this.prisma.warehouse.count({ where })]); return this.result(data, total, query); }
  async warehouse(id: string) { const data = await this.prisma.warehouse.findUnique({ where: { id }, include: { manager: { select: { id: true, name: true, email: true } } } }); if (!data) throw new NotFoundException('Warehouse not found'); return { success: true, data }; }
  async createWarehouse(dto: WarehouseDto, actor: AuthenticatedUser) { await this.manager(dto.managerId); try { const data = await this.prisma.warehouse.create({ data: { ...dto, status: dto.status ?? ActiveStatus.ACTIVE, isActive: dto.status !== ActiveStatus.INACTIVE } }); await this.audit(actor.id, 'WAREHOUSE_CREATED', 'WAREHOUSE', data.id); return { success: true, data, message: 'Warehouse created successfully' }; } catch { throw new ConflictException('Warehouse code already exists'); } }
  async updateWarehouse(id: string, dto: Partial<WarehouseDto>, actor: AuthenticatedUser) { await this.manager(dto.managerId); try { const data = await this.prisma.warehouse.update({ where: { id }, data: { ...dto, ...(dto.status ? { isActive: dto.status === ActiveStatus.ACTIVE } : {}) } }); await this.audit(actor.id, 'WAREHOUSE_UPDATED', 'WAREHOUSE', id); return { success: true, data }; } catch { throw new ConflictException('Warehouse could not be updated'); } }
  async statusWarehouse(id: string, status: ActiveStatus, actor: AuthenticatedUser) { return this.updateWarehouse(id, { status }, actor); }
  async deleteWarehouse(id: string, actor: AuthenticatedUser) { return this.statusWarehouse(id, ActiveStatus.INACTIVE, actor); }
  async assignManager(id: string, managerId: string | null, actor: AuthenticatedUser) { await this.manager(managerId ?? undefined); return this.updateWarehouse(id, { managerId: managerId ?? undefined }, actor); }

  async categories(query: ListDto) { const { limit, skip } = this.page(query); const where = query.search ? { name: { contains: query.search, mode: 'insensitive' as const } } : {}; const [data, total] = await Promise.all([this.prisma.category.findMany({ where, include: { parent: true, children: true, _count: { select: { products: true } } }, orderBy: { name: 'asc' }, skip, take: limit }), this.prisma.category.count({ where })]); return this.result(data, total, query); }
  async category(id: string) { const data = await this.prisma.category.findUnique({ where: { id }, include: { parent: true, children: true, products: { select: { id: true, name: true, sku: true } } } }); if (!data) throw new NotFoundException('Category not found'); return { success: true, data }; }
  async createCategory(dto: CategoryDto, actor: AuthenticatedUser) { if (dto.parentId === undefined) return this.createCategoryRecord(dto, actor); await this.category(dto.parentId); return this.createCategoryRecord(dto, actor); }
  private async createCategoryRecord(dto: CategoryDto, actor: AuthenticatedUser) { try { const data = await this.prisma.category.create({ data: dto }); await this.audit(actor.id, 'CATEGORY_CREATED', 'CATEGORY', data.id); return { success: true, data }; } catch { throw new ConflictException('Category name already exists at this level'); } }
  async updateCategory(id: string, dto: CategoryDto, actor: AuthenticatedUser) { if (dto.parentId === id) throw new BadRequestException('A category cannot be its own parent'); if (dto.parentId) { let current = dto.parentId; while (current) { if (current === id) throw new BadRequestException('Circular category hierarchy'); const parent = await this.prisma.category.findUnique({ where: { id: current }, select: { parentId: true } }); if (!parent) throw new NotFoundException('Parent category not found'); current = parent.parentId ?? ''; } } try { const data = await this.prisma.category.update({ where: { id }, data: dto }); await this.audit(actor.id, 'CATEGORY_UPDATED', 'CATEGORY', id); return { success: true, data }; } catch { throw new ConflictException('Category could not be updated'); } }
  async statusCategory(id: string, status: ActiveStatus, actor: AuthenticatedUser) { try { const data = await this.prisma.category.update({ where: { id }, data: { status } }); await this.audit(actor.id, 'CATEGORY_DEACTIVATED', 'CATEGORY', id); return { success: true, data }; } catch { throw new NotFoundException('Category not found'); } }
  async deleteCategory(id: string, actor: AuthenticatedUser) { const category = await this.prisma.category.findUnique({ where: { id }, include: { products: true, children: true } }); if (!category) throw new NotFoundException('Category not found'); if (category.products.length || category.children.length) throw new BadRequestException('Category with products or child categories must be reassigned before deletion'); const data = await this.prisma.category.update({ where: { id }, data: { status: ActiveStatus.INACTIVE } }); await this.audit(actor.id, 'CATEGORY_DEACTIVATED', 'CATEGORY', id); return { success: true, data }; }

  async products(query: ListDto & { categoryId?: string; brand?: string; sku?: string; barcode?: string }) { const { limit, skip } = this.page(query); const where = { ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' as const } }, { sku: { contains: query.search, mode: 'insensitive' as const } }] } : {}), ...(query.sku ? { sku: { contains: query.sku, mode: 'insensitive' as const } } : {}), ...(query.barcode ? { barcode: { contains: query.barcode, mode: 'insensitive' as const } } : {}), ...(query.categoryId ? { categoryId: query.categoryId } : {}), ...(query.brand ? { brand: { contains: query.brand, mode: 'insensitive' as const } } : {}), ...(query.status ? { status: query.status } : {}) }; const [data, total] = await Promise.all([this.prisma.product.findMany({ where, include: { category: true }, orderBy: { [this.sort(query.sortBy, ['name', 'sku', 'updatedAt'])]: query.sortOrder === 'desc' ? 'desc' : 'asc' }, skip, take: limit }), this.prisma.product.count({ where })]); return this.result(data, total, query); }
  async product(id: string) { const data = await this.prisma.product.findUnique({ where: { id }, include: { category: true } }); if (!data) throw new NotFoundException('Product not found'); return { success: true, data }; }
  async createProduct(dto: ProductDto, actor: AuthenticatedUser) { await this.category(dto.categoryId); try { const data = await this.prisma.product.create({ data: { ...dto, price: dto.sellingPrice, isActive: dto.status !== ProductStatus.INACTIVE } }); await this.audit(actor.id, 'PRODUCT_CREATED', 'PRODUCT', data.id); return { success: true, data }; } catch { throw new ConflictException('SKU or barcode already exists'); } }
  async updateProduct(id: string, dto: Partial<ProductDto>, actor: AuthenticatedUser) { if (dto.categoryId) await this.category(dto.categoryId); try { const data = await this.prisma.product.update({ where: { id }, data: { ...dto, ...(dto.sellingPrice !== undefined ? { price: dto.sellingPrice } : {}), ...(dto.status ? { isActive: dto.status === ProductStatus.ACTIVE } : {}) } }); await this.audit(actor.id, 'PRODUCT_UPDATED', 'PRODUCT', id); return { success: true, data }; } catch { throw new ConflictException('Product could not be updated'); } }
  async statusProduct(id: string, status: ProductStatus, actor: AuthenticatedUser) { return this.updateProduct(id, { status }, actor); }
  async deleteProduct(id: string, actor: AuthenticatedUser) { return this.statusProduct(id, ProductStatus.DISCONTINUED, actor); }

  async suppliers(query: ListDto) { const { limit, skip } = this.page(query); const where = { ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' as const } }, { code: { contains: query.search, mode: 'insensitive' as const } }] } : {}), ...(query.status ? { status: query.status } : {}) }; const [data, total] = await Promise.all([this.prisma.supplier.findMany({ where, orderBy: { [this.sort(query.sortBy, ['name', 'code', 'updatedAt'])]: query.sortOrder === 'desc' ? 'desc' : 'asc' }, skip, take: limit }), this.prisma.supplier.count({ where })]); return this.result(data, total, query); }
  async supplier(id: string) { const data = await this.prisma.supplier.findUnique({ where: { id } }); if (!data) throw new NotFoundException('Supplier not found'); return { success: true, data }; }
  async createSupplier(dto: SupplierDto, actor: AuthenticatedUser) { try { const data = await this.prisma.supplier.create({ data: dto }); await this.audit(actor.id, 'SUPPLIER_CREATED', 'SUPPLIER', data.id); return { success: true, data }; } catch { throw new ConflictException('Supplier code already exists'); } }
  async updateSupplier(id: string, dto: Partial<SupplierDto>, actor: AuthenticatedUser) { try { const data = await this.prisma.supplier.update({ where: { id }, data: dto }); await this.audit(actor.id, 'SUPPLIER_UPDATED', 'SUPPLIER', id); return { success: true, data }; } catch { throw new ConflictException('Supplier could not be updated'); } }
  async statusSupplier(id: string, status: ActiveStatus, actor: AuthenticatedUser) { return this.updateSupplier(id, { status }, actor); }
  async deleteSupplier(id: string, actor: AuthenticatedUser) { return this.statusSupplier(id, ActiveStatus.INACTIVE, actor); }
}
