import { IsEmail, IsEnum, IsInt, IsOptional, IsString, IsUrl, Min } from 'class-validator';

export enum ActiveStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE' }
export enum ProductStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', DISCONTINUED = 'DISCONTINUED' }
export class ListDto { @IsOptional() @IsString() search?: string; @IsOptional() @IsEnum(ActiveStatus) status?: ActiveStatus; @IsOptional() page?: number; @IsOptional() limit?: number; @IsOptional() @IsString() sortBy?: string; @IsOptional() @IsString() sortOrder?: string; }
export class WarehouseDto { @IsString() code!: string; @IsString() name!: string; @IsOptional() @IsString() description?: string; @IsOptional() @IsString() location?: string; @IsOptional() @IsString() address?: string; @IsOptional() @IsString() city?: string; @IsOptional() @IsString() state?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() postalCode?: string; @IsOptional() @IsString() phone?: string; @IsOptional() @IsEmail() email?: string; @IsOptional() @IsString() managerId?: string; @IsOptional() @IsInt() @Min(0) capacity?: number; @IsOptional() @IsEnum(ActiveStatus) status?: ActiveStatus; }
export class CategoryDto { @IsString() name!: string; @IsOptional() @IsString() description?: string; @IsOptional() @IsString() parentId?: string; @IsOptional() @IsEnum(ActiveStatus) status?: ActiveStatus; }
export class ProductDto { @IsString() sku!: string; @IsOptional() @IsString() barcode?: string; @IsString() name!: string; @IsOptional() @IsString() description?: string; @IsOptional() @IsString() brand?: string; @IsString() unit!: string; @IsOptional() @Min(0) weight?: number; @IsOptional() @Min(0) length?: number; @IsOptional() @Min(0) width?: number; @IsOptional() @Min(0) height?: number; @Min(0) costPrice!: number; @Min(0) sellingPrice!: number; @IsString() categoryId!: string; @IsOptional() @IsInt() @Min(0) reorderLevel?: number; @IsOptional() @IsInt() @Min(0) maximumStockLevel?: number; @IsOptional() @IsEnum(ProductStatus) status?: ProductStatus; }
export class SupplierDto { @IsString() code!: string; @IsString() name!: string; @IsOptional() @IsString() contactPerson?: string; @IsOptional() @IsEmail() email?: string; @IsOptional() @IsString() phone?: string; @IsOptional() @IsUrl() website?: string; @IsOptional() @IsString() address?: string; @IsOptional() @IsString() city?: string; @IsOptional() @IsString() state?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() postalCode?: string; @IsOptional() @IsString() paymentTerms?: string; @IsOptional() @IsString() notes?: string; @IsOptional() @IsEnum(ActiveStatus) status?: ActiveStatus; }
