import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from './prisma.service.js';
import type { AuthenticatedUser } from './auth.types.js';
import { ConsumeReservationDto, CreateReservationDto, ReasonDto, ReservationListDto } from './reservation.dto.js';

const transitions: Record<string, string[]> = { PENDING: ['ACTIVE', 'CANCELLED'], ACTIVE: ['PARTIALLY_CONSUMED', 'CONSUMED', 'RELEASED', 'CANCELLED', 'EXPIRED'], PARTIALLY_CONSUMED: ['PARTIALLY_CONSUMED', 'CONSUMED', 'RELEASED', 'CANCELLED', 'EXPIRED'], CONSUMED: [], RELEASED: [], CANCELLED: [], EXPIRED: [] };
const include = { warehouse: { select: { id: true, name: true, code: true } }, requestedBy: { select: { id: true, name: true, email: true } }, items: { include: { product: { select: { id: true, name: true, sku: true, barcode: true } } } } } as const;
@Injectable()
export class ReservationsService {
  constructor(private readonly prisma: PrismaService) {}
  private async warehouse(user: AuthenticatedUser, id: string) { const w = await this.prisma.warehouse.findUnique({ where: { id } }); if (!w || w.status !== 'ACTIVE') throw new NotFoundException('Warehouse not found or inactive'); if (user.role === 'WAREHOUSE_MANAGER' && w.managerId !== user.id) throw new ForbiddenException('Warehouse access is restricted to assigned warehouses'); return w; }
  private transition(status: string, next: string) { if (!transitions[status]?.includes(next)) throw new ConflictException(`Reservation cannot transition from ${status} to ${next}`); }
  private async audit(userId: string, action: string, id: string, details?: object) { await this.prisma.auditLog.create({ data: { userId, action, entity: 'RESERVATION', entityId: id, details } }); }
  private async number(tx: Prisma.TransactionClient) { return `RES-${String((await tx.reservation.count()) + 1).padStart(6, '0')}`; }
  async createTransferReservation(tx: Prisma.TransactionClient, transferId: string, warehouseId: string, requestedById: string, items: { productId: string; requestedQuantity: number }[]) {
    const reservation = await tx.reservation.create({ data: { reservationNumber: await this.number(tx), warehouseId, reservationType: 'TRANSFER', referenceType: 'TRANSFER', referenceId: transferId, requestedById, status: 'ACTIVE', items: { create: items.map((item) => ({ productId: item.productId, requestedQuantity: item.requestedQuantity, reservedQuantity: item.requestedQuantity })) } }, include });
    return reservation;
  }
  async consumeTransferReservation(tx: Prisma.TransactionClient, transferId: string) {
    const reservation = await tx.reservation.findFirst({ where: { referenceType: 'TRANSFER', referenceId: transferId, status: 'ACTIVE' }, include: { items: true } });
    if (!reservation) throw new ConflictException('Transfer reservation not found or already consumed');
    for (const item of reservation.items) {
      const remaining = item.reservedQuantity - item.consumedQuantity - item.releasedQuantity;
      await tx.reservationItem.update({ where: { id: item.id }, data: { consumedQuantity: { increment: remaining } } });
    }
    await tx.reservation.update({ where: { id: reservation.id }, data: { status: 'CONSUMED' } });
    return reservation;
  }
  async releaseTransferReservation(tx: Prisma.TransactionClient, transferId: string) {
    const reservation = await tx.reservation.findFirst({ where: { referenceType: 'TRANSFER', referenceId: transferId, status: 'ACTIVE' }, include: { items: true } });
    if (!reservation) return;
    for (const item of reservation.items) {
      const remaining = item.reservedQuantity - item.consumedQuantity - item.releasedQuantity;
      if (remaining > 0) await tx.reservationItem.update({ where: { id: item.id }, data: { releasedQuantity: { increment: remaining } } });
    }
    await tx.reservation.update({ where: { id: reservation.id }, data: { status: 'RELEASED' } });
  }
  async createReservation(dto: CreateReservationDto, user: AuthenticatedUser) { await this.warehouse(user, dto.warehouseId); if (!dto.items.length || new Set(dto.items.map((x) => x.productId)).size !== dto.items.length) throw new BadRequestException('Reservation must contain unique products'); if (dto.expiresAt && new Date(dto.expiresAt) <= new Date()) throw new BadRequestException('Expiration must be in the future'); const products = await this.prisma.product.findMany({ where: { id: { in: dto.items.map((x) => x.productId) }, isActive: true, status: 'ACTIVE' } }); if (products.length !== dto.items.length) throw new BadRequestException('All products must be active'); const data = await this.prisma.$transaction(async (tx) => tx.reservation.create({ data: { reservationNumber: await this.number(tx), warehouseId: dto.warehouseId, reservationType: dto.reservationType, referenceType: dto.referenceType, referenceId: dto.referenceId, requestedById: user.id, expiresAt: dto.expiresAt ? new Date(dto.expiresAt) : undefined, notes: dto.notes, items: { create: dto.items.map((x) => ({ productId: x.productId, requestedQuantity: x.quantity })) } }, include })); await this.audit(user.id, 'RESERVATION_CREATED', data.id, { warehouseId: dto.warehouseId }); return { success: true, data }; }
  async list(q: ReservationListDto, user: AuthenticatedUser) { const page = Math.max(1, Number(q.page) || 1); const limit = Math.min(100, Math.max(1, Number(q.limit) || 20)); const assigned = user.role === 'WAREHOUSE_MANAGER' ? await this.prisma.warehouse.findMany({ where: { managerId: user.id }, select: { id: true } }) : []; const where = { ...(assigned.length ? { warehouseId: { in: assigned.map((x) => x.id) } } : {}), ...(q.warehouseId ? { warehouseId: q.warehouseId } : {}), ...(q.status ? { status: q.status } : {}), ...(q.reservationType ? { reservationType: q.reservationType } : {}), ...(q.productId ? { items: { some: { productId: q.productId } } } : {}), ...(q.search ? { OR: [{ reservationNumber: { contains: q.search, mode: 'insensitive' as const } }, { referenceId: { contains: q.search, mode: 'insensitive' as const } }, { items: { some: { product: { OR: [{ name: { contains: q.search, mode: 'insensitive' as const } }, { sku: { contains: q.search, mode: 'insensitive' as const } }] } } } }] } : {}) }; const [data, total] = await Promise.all([this.prisma.reservation.findMany({ where, include, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit }), this.prisma.reservation.count({ where })]); return { success: true, data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async get(id: string, user: AuthenticatedUser) { const data = await this.prisma.reservation.findUnique({ where: { id }, include }); if (!data) throw new NotFoundException('Reservation not found'); await this.warehouse(user, data.warehouseId); return { success: true, data }; }
  async create(dto: CreateReservationDto, user: AuthenticatedUser) { await this.warehouse(user, dto.warehouseId); if (!dto.items.length || new Set(dto.items.map((x) => x.productId)).size !== dto.items.length) throw new BadRequestException('Reservation must contain unique products'); if (dto.expiresAt && new Date(dto.expiresAt) <= new Date()) throw new BadRequestException('Expiration must be in the future'); const products = await this.prisma.product.findMany({ where: { id: { in: dto.items.map((x) => x.productId) }, isActive: true, status: 'ACTIVE' } }); if (products.length !== dto.items.length) throw new BadRequestException('All products must be active'); const data = await this.prisma.$transaction((tx) => tx.reservation.create({ data: { reservationNumber: '', warehouseId: dto.warehouseId, reservationType: dto.reservationType, referenceType: dto.referenceType, referenceId: dto.referenceId, requestedById: user.id, expiresAt: dto.expiresAt ? new Date(dto.expiresAt) : undefined, notes: dto.notes, items: { create: dto.items.map((x) => ({ productId: x.productId, requestedQuantity: x.quantity })) } }, include })).catch(async () => { const number = await this.prisma.$transaction(async (tx) => { const reservationNumber = await this.number(tx); return tx.reservation.create({ data: { reservationNumber, warehouseId: dto.warehouseId, reservationType: dto.reservationType, referenceType: dto.referenceType, referenceId: dto.referenceId, requestedById: user.id, expiresAt: dto.expiresAt ? new Date(dto.expiresAt) : undefined, notes: dto.notes, items: { create: dto.items.map((x) => ({ productId: x.productId, requestedQuantity: x.quantity })) } }, include }); }); return number; }); await this.audit(user.id, 'RESERVATION_CREATED', data.id, { warehouseId: dto.warehouseId }); return { success: true, data }; }
  async activate(id: string, user: AuthenticatedUser) { const reservation = await this.raw(id); await this.warehouse(user, reservation.warehouseId); this.transition(reservation.status, 'ACTIVE'); try { const data = await this.prisma.$transaction(async (tx) => { for (const item of reservation.items) { const inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId: reservation.warehouseId, productId: item.productId } } }); if (!inventory || inventory.quantityOnHand - inventory.quantityReserved < item.requestedQuantity) throw new ConflictException('Insufficient available stock'); const changed = await tx.inventory.updateMany({ where: { id: inventory.id, quantityReserved: inventory.quantityReserved }, data: { quantityReserved: { increment: item.requestedQuantity } } }); if (changed.count !== 1) throw new ConflictException('Inventory changed concurrently; retry activation'); await tx.reservationItem.update({ where: { id: item.id }, data: { reservedQuantity: item.requestedQuantity } }); } return tx.reservation.update({ where: { id, status: 'PENDING' }, data: { status: 'ACTIVE' }, include }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); await this.audit(user.id, 'RESERVATION_ACTIVATED', id); return { success: true, data }; } catch (e) { if (e instanceof ConflictException) throw e; throw new ConflictException('Reservation activation failed'); } }
  private async raw(id: string) { const data = await this.prisma.reservation.findUnique({ where: { id }, include: { items: true } }); if (!data) throw new NotFoundException('Reservation not found'); return data; }
  async release(id: string, user: AuthenticatedUser) { const r = await this.raw(id); await this.warehouse(user, r.warehouseId); this.transition(r.status, 'RELEASED'); const data = await this.prisma.$transaction(async (tx) => { for (const item of r.items) { const remaining = item.reservedQuantity - item.consumedQuantity - item.releasedQuantity; if (remaining > 0) await tx.inventory.update({ where: { warehouseId_productId: { warehouseId: r.warehouseId, productId: item.productId } }, data: { quantityReserved: { decrement: remaining } } }); await tx.reservationItem.update({ where: { id: item.id }, data: { releasedQuantity: { increment: remaining } } }); } return tx.reservation.update({ where: { id }, data: { status: 'RELEASED' }, include }); }); await this.audit(user.id, 'RESERVATION_RELEASED', id); return { success: true, data }; }
  async consume(id: string, dto: ConsumeReservationDto, user: AuthenticatedUser) { const r = await this.raw(id); await this.warehouse(user, r.warehouseId); if (!['ACTIVE', 'PARTIALLY_CONSUMED'].includes(r.status)) throw new ConflictException('Reservation cannot be consumed in its current state'); const requested = new Map(dto.items.map((x) => [x.productId, x.quantity])); const data = await this.prisma.$transaction(async (tx) => { let complete = true; for (const item of r.items) { const amount = requested.get(item.productId) ?? 0; const remaining = item.reservedQuantity - item.consumedQuantity - item.releasedQuantity; if (amount > remaining) throw new ConflictException('Consumption exceeds remaining reserved quantity'); if (amount) { const inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId: r.warehouseId, productId: item.productId } } }); if (!inventory || inventory.quantityOnHand < amount || inventory.quantityReserved < amount) throw new ConflictException('Reserved stock is unavailable'); await tx.inventory.update({ where: { id: inventory.id }, data: { quantityOnHand: { decrement: amount }, quantityReserved: { decrement: amount } } }); await tx.stockTransaction.create({ data: { inventoryId: inventory.id, warehouseId: r.warehouseId, productId: item.productId, transactionType: 'RESERVATION', quantity: amount, quantityBefore: inventory.quantityOnHand, quantityAfter: inventory.quantityOnHand - amount, reason: `Reservation ${r.reservationNumber}`, referenceType: 'RESERVATION', referenceId: id, performedBy: user.id } }); await tx.reservationItem.update({ where: { id: item.id }, data: { consumedQuantity: { increment: amount } } }); } if (remaining - amount > 0) complete = false; } const status = complete ? 'CONSUMED' : 'PARTIALLY_CONSUMED'; return tx.reservation.update({ where: { id }, data: { status }, include }); }); await this.audit(user.id, 'RESERVATION_CONSUMED', id); return { success: true, data }; }
  async cancel(id: string, dto: ReasonDto, user: AuthenticatedUser) { const r = await this.raw(id); await this.warehouse(user, r.warehouseId); if (['CONSUMED', 'RELEASED', 'EXPIRED', 'CANCELLED'].includes(r.status)) throw new ConflictException('Reservation cannot be cancelled in its current state'); if (r.status === 'ACTIVE' || r.status === 'PARTIALLY_CONSUMED') await this.release(id, user); const data = await this.prisma.reservation.update({ where: { id }, data: { status: 'CANCELLED' }, include }); await this.audit(user.id, 'RESERVATION_CANCELLED', id, { reason: dto.reason }); return { success: true, data }; }
  async summary(warehouseId: string | undefined, user: AuthenticatedUser) { const result = await this.list({ warehouseId, limit: 100 }, user); const data = result.data; return { success: true, data: { total: data.length, active: data.filter((x) => x.status === 'ACTIVE').length, pending: data.filter((x) => x.status === 'PENDING').length, partiallyConsumed: data.filter((x) => x.status === 'PARTIALLY_CONSUMED').length, consumed: data.filter((x) => x.status === 'CONSUMED').length, released: data.filter((x) => x.status === 'RELEASED').length, expired: data.filter((x) => x.status === 'EXPIRED').length } }; }
  async expireReservations() { const candidates = await this.prisma.reservation.findMany({ where: { status: { in: ['ACTIVE', 'PARTIALLY_CONSUMED'] }, expiresAt: { lte: new Date() } }, include: { items: true } }); let expired = 0; for (const reservation of candidates) { try { await this.prisma.$transaction(async (tx) => { const current = await tx.reservation.findUnique({ where: { id: reservation.id }, include: { items: true } }); if (!current || !['ACTIVE', 'PARTIALLY_CONSUMED'].includes(current.status) || !current.expiresAt || current.expiresAt > new Date()) return; for (const item of current.items) { const remaining = item.reservedQuantity - item.consumedQuantity - item.releasedQuantity; if (remaining > 0) { await tx.inventory.update({ where: { warehouseId_productId: { warehouseId: current.warehouseId, productId: item.productId } }, data: { quantityReserved: { decrement: remaining } } }); await tx.reservationItem.update({ where: { id: item.id }, data: { releasedQuantity: { increment: remaining } } }); } } await tx.reservation.update({ where: { id: current.id }, data: { status: 'EXPIRED' } }); await tx.auditLog.create({ data: { userId: current.requestedById, action: 'RESERVATION_EXPIRED', entity: 'RESERVATION', entityId: current.id, details: { reservationNumber: current.reservationNumber } } }); }); expired += 1; } catch { /* Another worker may have completed this reservation. */ } } return { success: true, data: { expired } }; }
}
