// Stock Count Types
export const STOCK_COUNT_TYPES = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
  CYCLE: 'CYCLE',
  SPOT_CHECK: 'SPOT_CHECK',
} as const;

// Stock Count Statuses
export const STOCK_COUNT_STATUSES = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

// Variance Severity
export const VARIANCE_SEVERITY = {
  NONE: 'NONE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

// Variance Thresholds (percentage)
export const VARIANCE_THRESHOLDS = {
  NONE_MAX: 0.01,
  LOW_MAX: 2,
  MEDIUM_MAX: 5,
  HIGH_MAX: 10,
  CRITICAL_MIN: 10,
} as const;

// Reconciliation Status
export const RECONCILIATION_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  EXECUTED: 'EXECUTED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

// Adjustment Types
export const ADJUSTMENT_TYPES = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  NO_CHANGE: 'NO_CHANGE',
} as const;

// Status Transitions - what statuses can transition to what
export const VALID_TRANSITIONS = {
  [STOCK_COUNT_STATUSES.DRAFT]: [STOCK_COUNT_STATUSES.IN_PROGRESS, STOCK_COUNT_STATUSES.CANCELLED],
  [STOCK_COUNT_STATUSES.IN_PROGRESS]: [STOCK_COUNT_STATUSES.SUBMITTED, STOCK_COUNT_STATUSES.CANCELLED],
  [STOCK_COUNT_STATUSES.SUBMITTED]: [STOCK_COUNT_STATUSES.UNDER_REVIEW, STOCK_COUNT_STATUSES.IN_PROGRESS],
  [STOCK_COUNT_STATUSES.UNDER_REVIEW]: [STOCK_COUNT_STATUSES.APPROVED, STOCK_COUNT_STATUSES.REJECTED],
  [STOCK_COUNT_STATUSES.APPROVED]: [STOCK_COUNT_STATUSES.COMPLETED],
  [STOCK_COUNT_STATUSES.REJECTED]: [STOCK_COUNT_STATUSES.IN_PROGRESS],
  [STOCK_COUNT_STATUSES.COMPLETED]: [],
  [STOCK_COUNT_STATUSES.CANCELLED]: [],
} as const;
