import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from './prisma.service.js';
import type { AuthenticatedUser } from './auth.types.js';
import { CreateTransferDto, ReceiveTransferDto, ReasonDto, TransferListDto } from './transfer.dto.js';

const transitions: Record<string, string[]> = { DRAFT: ['PENDING_APPROVAL', 'CANCELLED'], PENDING_APPROVAL: ['APPROVED', 'REJECTED', 'CANCELLED'], APPROVED: ['IN_TRANSIT', 'CANCELLED'], IN_TRANSIT: ['RECEIVED'], RECEIVED: [], REJECTED: [], CANCELLED: [] };
const include = { sourceWarehouse: { select: { id: true, code: true, name: true } }, destinationWarehouse: { select: { id: true, code: true, name: true } }, requestedBy: { select: { id: true, name: true, email: true } }, approvedBy: { select: { id: true, name: true, email: true } }, receivedBy: { select: { id: true, name: true, email: true } }, items: { include: { product: { select: { id: true, sku: true, name: true, barcode: true } } } } } as const;
@Injectable()
export class TransfersService {
  constructor(private readonly prisma: PrismaService) {}
  private async audit(userId: string, action: string, transferId: string, details?: object) { await this.prisma.auditLog.create({ data: { userId, action, entity: 'TRANSFER', entityId: transferId, details } }); }
  private async warehouse(user: AuthenticatedUser, id: string) { const warehouse = await this.prisma.warehouse.findUnique({ where: { id } }); if (!warehouse || warehouse.status !== 'ACTIVE') throw new NotFoundException('Warehouse not found or inactive'); if (user.role === 'WAREHOUSE_MANAGER' && warehouse.managerId !== user.id) throw new ForbiddenException('Warehouse access is restricted to assigned warehouses'); return warehouse; }
  private transition(current: string, next: string) { if (!transitions[current]?.includes(next)) throw new ConflictException(`Transfer cannot transition from ${current} to ${next}`); }
  private async nextNumber(tx: Prisma.TransactionClient) { const count = await tx.stockTransfer.count(); return `TRF-${String(count + 1).padStart(6, '0')}`; }
  async list(q: TransferListDto, user: AuthenticatedUser) { const page = Math.max(1, Number(q.page) || 1); const limit = Math.min(100, Math.max(1, Number(q.limit) || 20)); const assigned = user.role === 'WAREHOUSE_MANAGER' ? await this.prisma.warehouse.findMany({ where: { managerId: user.id }, select: { id: true } }) : []; const ids = assigned.map((x) => x.id); const where = { ...(user.role === 'WAREHOUSE_MANAGER' ? { OR: [{ sourceWarehouseId: { in: ids } }, { destinationWarehouseId: { in: ids } }] } : {}), ...(q.status ? { status: q.status } : {}), ...(q.sourceWarehouseId ? { sourceWarehouseId: q.sourceWarehouseId } : {}), ...(q.destinationWarehouseId ? { destinationWarehouseId: q.destinationWarehouseId } : {}), ...(q.search ? { OR: [{ transferNumber: { contains: q.search, mode: 'insensitive' as const } }, { items: { some: { product: { OR: [{ name: { contains: q.search, mode: 'insensitive' as const } }, { sku: { contains: q.search, mode: 'insensitive' as const } }] } } } }] } : {}) }; const [data, total] = await Promise.all([this.prisma.stockTransfer.findMany({ where, include, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit }), this.prisma.stockTransfer.count({ where })]); return { success: true, data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async get(id: string, user: AuthenticatedUser) { const data = await this.prisma.stockTransfer.findUnique({ where: { id }, include }); if (!data) throw new NotFoundException('Transfer not found'); await this.warehouse(user, data.sourceWarehouseId); await this.warehouse(user, data.destinationWarehouseId); return { success: true, data }; }
  async create(dto: CreateTransferDto, user: AuthenticatedUser) { if (dto.sourceWarehouseId === dto.destinationWarehouseId) throw new ConflictException('Source and destination warehouses must be different'); await this.warehouse(user, dto.sourceWarehouseId); await this.warehouse(user, dto.destinationWarehouseId); if (!dto.items.length || new Set(dto.items.map((x) => x.productId)).size !== dto.items.length) throw new BadRequestException('Transfer must contain unique products'); const products = await this.prisma.product.findMany({ where: { id: { in: dto.items.map((x) => x.productId) }, status: 'ACTIVE', isActive: true } }); if (products.length !== dto.items.length) throw new BadRequestException('All products must be active'); try { const data = await this.prisma.$transaction(async (tx) => { const transferNumber = await this.nextNumber(tx); return tx.stockTransfer.create({ data: { transferNumber, sourceWarehouseId: dto.sourceWarehouseId, destinationWarehouseId: dto.destinationWarehouseId, requestedById: user.id, notes: dto.notes, items: { create: dto.items.map((x) => ({ productId: x.productId, requestedQuantity: x.requestedQuantity })) } }, include }); }); await this.audit(user.id, 'TRANSFER_CREATED', data.id, { sourceWarehouseId: dto.sourceWarehouseId, destinationWarehouseId: dto.destinationWarehouseId }); return { success: true, data }; } catch { throw new ConflictException('Transfer number or transfer data conflicts'); } }
  async submit(id: string, user: AuthenticatedUser) { const transfer = await this.findRaw(id); if (transfer.requestedById !== user.id && user.role !== 'ADMIN') throw new ForbiddenException('Only the requester or an administrator can submit this transfer'); this.transition(transfer.status, 'PENDING_APPROVAL'); const data = await this.prisma.stockTransfer.update({ where: { id }, data: { status: 'PENDING_APPROVAL' }, include }); await this.audit(user.id, 'TRANSFER_SUBMITTED', id); return { success: true, data }; }
  private async findRaw(id: string) { const transfer = await this.prisma.stockTransfer.findUnique({ where: { id }, include: { items: true } }); if (!transfer) throw new NotFoundException('Transfer not found'); return transfer; }
  async approve(id: string, user: AuthenticatedUser) { const transfer = await this.findRaw(id); await this.warehouse(user, transfer.sourceWarehouseId); await this.warehouse(user, transfer.destinationWarehouseId); this.transition(transfer.status, 'APPROVED'); try { const data = await this.prisma.$transaction(async (tx) => { for (const item of transfer.items) { const inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId: transfer.sourceWarehouseId, productId: item.productId } } }); if (!inventory || inventory.quantityOnHand - inventory.quantityReserved < item.requestedQuantity) throw new ConflictException('Insufficient available stock'); const updated = await tx.inventory.updateMany({ where: { id: inventory.id, quantityReserved: inventory.quantityReserved }, data: { quantityReserved: { increment: item.requestedQuantity } } }); if (updated.count !== 1) throw new ConflictException('Inventory changed concurrently; retry approval'); await tx.stockReservation.create({ data: { userId: user.id, productId: item.productId, warehouseId: transfer.sourceWarehouseId, quantity: item.requestedQuantity, status: 'ACTIVE', transferId: id } }); } return tx.stockTransfer.update({ where: { id, status: 'PENDING_APPROVAL' }, data: { status: 'APPROVED', approvedById: user.id, approvedAt: new Date() }, include }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); await this.audit(user.id, 'TRANSFER_APPROVED', id); return { success: true, data }; } catch (error) { if (error instanceof ConflictException) throw error; throw new ConflictException('Transfer approval failed'); } }
  async reject(id: string, dto: ReasonDto, user: AuthenticatedUser) { const transfer = await this.findRaw(id); this.transition(transfer.status, 'REJECTED'); const data = await this.prisma.stockTransfer.update({ where: { id }, data: { status: 'REJECTED', rejectionReason: dto.reason }, include }); await this.audit(user.id, 'TRANSFER_REJECTED', id, { reason: dto.reason }); return { success: true, data }; }
  async dispatch(id: string, user: AuthenticatedUser) { const transfer = await this.findRaw(id); await this.warehouse(user, transfer.sourceWarehouseId); this.transition(transfer.status, 'IN_TRANSIT'); try { const data = await this.prisma.$transaction(async (tx) => { for (const item of transfer.items) { const inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId: transfer.sourceWarehouseId, productId: item.productId } } }); if (!inventory || inventory.quantityReserved < item.requestedQuantity || inventory.quantityOnHand < item.requestedQuantity) throw new ConflictException('Reserved stock is unavailable'); const next = inventory.quantityOnHand - item.requestedQuantity; await tx.inventory.update({ where: { id: inventory.id }, data: { quantityOnHand: next, quantityReserved: { decrement: item.requestedQuantity } } }); await tx.stockTransaction.create({ data: { inventoryId: inventory.id, warehouseId: transfer.sourceWarehouseId, productId: item.productId, transactionType: 'TRANSFER_OUT', quantity: item.requestedQuantity, quantityBefore: inventory.quantityOnHand, quantityAfter: next, reason: `Transfer ${transfer.transferNumber}`, referenceType: 'TRANSFER', referenceId: id, performedBy: user.id } }); await tx.stockReservation.updateMany({ where: { transferId: id, productId: item.productId, status: 'ACTIVE' }, data: { status: 'CONSUMED' } }); await tx.stockTransferItem.update({ where: { id: item.id }, data: { shippedQuantity: item.requestedQuantity } }); } return tx.stockTransfer.update({ where: { id, status: 'APPROVED' }, data: { status: 'IN_TRANSIT', shippedAt: new Date() }, include }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); await this.audit(user.id, 'TRANSFER_DISPATCHED', id); return { success: true, data }; } catch (error) { if (error instanceof ConflictException) throw error; throw new ConflictException('Transfer dispatch failed'); } }
  async receive(id: string, dto: ReceiveTransferDto, user: AuthenticatedUser) { const transfer = await this.findRaw(id); await this.warehouse(user, transfer.destinationWarehouseId); this.transition(transfer.status, 'RECEIVED'); const values = new Map(dto.items.map((x) => [x.itemId, x.receivedQuantity])); try { const data = await this.prisma.$transaction(async (tx) => { for (const item of transfer.items) { const received = values.get(item.id) ?? item.requestedQuantity; if (received < 0 || received > item.requestedQuantity) throw new BadRequestException('Received quantity must be between zero and requested quantity'); let inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId: transfer.destinationWarehouseId, productId: item.productId } } }); if (!inventory) inventory = await tx.inventory.create({ data: { warehouseId: transfer.destinationWarehouseId, productId: item.productId } }); const next = inventory.quantityOnHand + received; await tx.inventory.update({ where: { id: inventory.id }, data: { quantityOnHand: next } }); await tx.stockTransaction.create({ data: { inventoryId: inventory.id, warehouseId: transfer.destinationWarehouseId, productId: item.productId, transactionType: 'TRANSFER_IN', quantity: received, quantityBefore: inventory.quantityOnHand, quantityAfter: next, reason: `Transfer ${transfer.transferNumber}`, referenceType: 'TRANSFER', referenceId: id, performedBy: user.id } }); await tx.stockTransferItem.update({ where: { id: item.id }, data: { receivedQuantity: received, shippedQuantity: item.requestedQuantity } }); } return tx.stockTransfer.update({ where: { id, status: 'IN_TRANSIT' }, data: { status: 'RECEIVED', receivedById: user.id, receivedAt: new Date() }, include }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); await this.audit(user.id, 'TRANSFER_RECEIVED', id); return { success: true, data }; } catch (error) { if (error instanceof BadRequestException) throw error; throw new ConflictException('Transfer receiving failed'); } }
  async cancel(id: string, dto: ReasonDto, user: AuthenticatedUser) { const transfer = await this.findRaw(id); await this.warehouse(user, transfer.sourceWarehouseId); this.transition(transfer.status, 'CANCELLED'); const data = await this.prisma.$transaction(async (tx) => { if (transfer.status === 'APPROVED') for (const item of transfer.items) { const inventory = await tx.inventory.findUnique({ where: { warehouseId_productId: { warehouseId: transfer.sourceWarehouseId, productId: item.productId } } }); if (inventory) await tx.inventory.update({ where: { id: inventory.id }, data: { quantityReserved: { decrement: item.requestedQuantity } } }); await tx.stockReservation.updateMany({ where: { transferId: id, status: 'ACTIVE' }, data: { status: 'CANCELLED' } }); } return tx.stockTransfer.update({ where: { id }, data: { status: 'CANCELLED', cancellationReason: dto.reason }, include }); }); await this.audit(user.id, 'TRANSFER_CANCELLED', id); return { success: true, data }; }
}
