import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Search, UserPlus } from "lucide-react";
import { apiClient } from "@/api/client";
import { useAuth } from "@/auth/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
export function Users() { const { can } = useAuth(); const [search, setSearch] = useState(""); const users = useQuery({ queryKey: ["users", search], queryFn: () => apiClient.get(`/users?search=${encodeURIComponent(search)}`) }); if (!can("USER_VIEW")) return <div className="py-20 text-center"><h2 className="text-2xl font-semibold">Access denied</h2><p className="mt-2 text-muted-foreground">You do not have permission to view users.</p></div>; const data = users.data?.data ?? []; return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold tracking-tight">User management</h2><p className="text-muted-foreground">Control access across your organization.</p></div>{can("USER_CREATE") && <Button><UserPlus size={16} /> Create user</Button>}</div><Card><CardHeader><CardTitle className="flex items-center justify-between gap-4"><span>Directory</span><div className="relative w-full max-w-xs"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search users" value={search} onChange={(event) => setSearch(event.target.value)} /></div></CardTitle></CardHeader><CardContent>{users.isLoading ? <p className="py-8 text-center text-muted-foreground">Loading users...</p> : <Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{data.map((item: { id: string; name: string; email: string; role: string; isActive: boolean; createdAt: string }) => <TableRow key={item.id}><TableCell className="font-medium">{item.name}</TableCell><TableCell>{item.email}</TableCell><TableCell>{item.role}</TableCell><TableCell><Badge variant={item.isActive ? "default" : "secondary"}>{item.isActive ? "Active" : "Inactive"}</Badge></TableCell><TableCell>{new Date(item.createdAt).toLocaleDateString()}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></div>; }
